### ISSUE TITLE
上传图片后显示太大

### ISSUE THREAD

**Issue by hezhongfeng** [brenner8023/vue-mask#1]
![下载](https://user-images.githubusercontent.com/12163050/74813232-007dc700-5330-11ea-8428-5936165e106b.png)
造成和口罩大小不匹配，而且口罩的大小和位置不能随意改变

**Comment by brenner8023** [comment]
我做的是h5，没有适配pc端，请在移动端使用。

**Comment by brenner8023** [comment]
> ![下载](https://user-images.githubusercontent.com/12163050/74813232-007dc700-5330-11ea-8428-5936165e106b.png)
> 造成和口罩大小不匹配，而且口罩的大小和位置不能随意改变

我做的是h5，没有适配pc端，请在移动端使用。

**Comment by hezhongfeng** [comment]
好的
